#!/bin/bash

#
#          ___..----'---`----..___
#          ===================================_
#            `---.._______..---'.        -_ _  _______________
#                                \ _______ (_||__)____________)
#                         *----   -_          _______\_____\
#                                   -________/
#
#
# Triggered during logout to run scripts:
#
# Script Types:
# - onAnyLogout: runs scripts everytime a logout happens
#
# Host type:
# defined as a child of the script type, it tells what is the which kind of host it should
# be executed, this is done by reading the env var $UMEDIA_HOST_TYPE. In case a script
# is meant to be executed in any host then place it under "any" (rather then duplicating it
# accross the hosts...)
#
# Script conventions:
# make sure the scripts have the shebang (#!) and are set as executable.

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# logout types
logoutTypes="onAnyLogout"

# running the login scripts
for logoutType in $logoutTypes ; do

  logoutAnyScriptPath="$dir/$logoutType/any/$UCORE_OS/$UCORE_OS_VERSION"
  logoutHostTypeScriptPath="$dir/$logoutType/$UMEDIA_HOST_TYPE/$UCORE_OS/$UCORE_OS_VERSION"

  for logoutScriptPath in $logoutAnyScriptPath $logoutHostTypeScriptPath ; do
    for executable in $logoutScriptPath/* ; do
      echo "$executable"
      # making sure it's an executable
      if [[ -x "$executable" ]]; then
        eval $executable
      fi
    done
  done
done
