#!/bin/bash

# Shows a dialogue listing features as checkboxes (usually this function
# should be driven by the enviroment $UMEDIA_SHOW_FEATURE_CHOOSER)
#
# first argument: string containing the disabled features (separated by space)
# second argument: string containing the enabled features (separated by space)
# thrid argument (optional): optional string containing the title for the dialogue
# result: string containing the features that were enabled in the end (separated by space)
function featureChooser()
{

  # arguments
  local disabledFeatures=$1
  local enabledFeatures=$2
  local title=$3

  if [ -z "$title" ]; then
    title="Feature Chooser"
  fi

  # disabled features
  local disabledFeaturesString=""
  for disabledFeature in $disabledFeatures ; do
    disabledFeaturesString+="FALSE $disabledFeature "
  done;

  # enabled features
  local enabledFeaturesString=""
  for enabledFeature in $enabledFeatures ; do
    enabledFeaturesString+="TRUE $enabledFeature "
  done;

  # since we are setting enviroments for zenity, lets run it through a subshell
  (
    # this is necessary to avoid an issue in kde that does not allow the checkboxes to be toggled
    if [ "$UCORE_OS_VERSION" == "centos7" ]; then
      export GTK_THEME="/usr/share/themes/Default/gtk-3.0/gtk-keys.css"
    fi

    # showing a dialogue
    echo $(zenity --title "UMedia: $title" --list --checklist --column "Enable" --column "Plugin Name" $disabledFeaturesString $enabledFeaturesString --separator=" ")
  )
}
