#!/bin/bash

# Shows a dialogue listing features as checkboxes
#
# first argument: string containing the disabled features (separated by space)
# second argument: string containing the enabled features (separated by space)
# thrid argument (optional): optional string containing the title for the dialogue
# result: string containing the features that were enabled in the end (separated by space)
function featureChooser()
{

  # arguments
  local disabledFeatures=$1
  local enabledFeatures=$2
  local title=$3

  if [ -z "$title" ]; then
    title="Feature Chooser"
  fi

  # disabled features
  local disabledFeaturesString=""
  for disabledFeature in $disabledFeatures ; do
    disabledFeaturesString+="FALSE $disabledFeature "
  done;

  # enabled features
  local enabledFeaturesString=""
  for enabledFeature in $enabledFeatures ; do
    enabledFeaturesString+="TRUE $enabledFeature "
  done;

  # showing the modeal dialogue
  echo $(zenity --title "UMedia: $title" --list --checklist  --column "Enable" --column "Plugin Name" $disabledFeaturesString $enabledFeaturesString --separator=" ")
}
