#!/bin/bash

# creating rv config folder
configFolder=$HOME/.config/TweakSoftware
if ! [ -z "$configFolder" ]; then
    mkdir -p $configFolder
fi

# copying the initial config file config file
cp $UCORE_ROOT/settings/defaultUserConfigs/RV/RV.conf $configFolder/RV.conf
