#!/usr/bin/env python

import os
import json


def writeCurrentEnv(installationEnv):
    """
    Writes a json file with the current environment
    """
    with open(installationEnv, 'w') as f:
        jsonData = json.dumps(dict(os.environ), sort_keys=True, indent=4, separators=(',', ': '))
        f.write(jsonData)

if __name__ == "__main__":
    installationEnv = os.path.join(os.environ['UMEDIA_LOCAL_DATA'], 'installationEnv.json');
    writeCurrentEnv(installationEnv)
