#!/bin/bash

# creating rv config folder
configFolder=$HOME/.config/TweakSoftware
if ! [ -d "$configFolder" ]; then
    mkdir -p $configFolder
fi

# copying the initial config file config file
cp $( locres ucore/$UCORE_VERSION )/settings/defaultUserConfigs/RV/RV.conf $configFolder/RV.conf
