#!/bin/bash

# creating neatvideo config folder
configFolder=$HOME/.config/ABSoft

# only doing it in case the configation does not exist
if ! [ -d "$configFolder" ]; then
    mkdir -p $configFolder
    cp $( locres ucore/$UCORE_VERSION )/settings/defaultUserConfigs/neatVideo/NeatVideo4-OFX.conf $configFolder/
fi
