#!/bin/bash

# custom environment variables that don't belong to any particular ucore category,
# such as license environments, auxiliary env variables, etc...

# shotgun python location
# (currently the location of 'shotgun python' is also used externally under job configuration:
# <project>/config/toolkit/config/core/interpreter_Linux.cfg)
export UCORE_SHOTGUN_PYTHON_EXECUTABLE=$UAPPS_ROOT/shotgunDesktop/$UCORE_SHOTGUNDESKTOP_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/Python/bin/python

# nuke license location
export FOUNDRY_LICENSE_FILE=$UCORE_ROOT/settings/licenses/nuke/nuke.lic

# mocha pro license server
export ISL_LICENSE_FILE=27000@umedia-ls01
