#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
wrappersDir="$( dirname $dir )"

# checking if dev root is set
if [ -z "$UCORE_ROOT" ]; then
    echo "UCORE_ROOT IS NOT SET"
    exit 1
fi

# building ucore paths
newBasePath=""

# adding wrappers to the environment
if ! [ -z "$UCORE_LOCAL" ]; then
    if [ -d "$UCORE_LOCAL/wrappers" ]; then
        newBasePath+="$UCORE_LOCAL/wrappers:"
    fi
fi

newBasePath+="$wrappersDir/wrappers:"
addBasePath=true

# checking if UCORE_PATH is already set
if ! [ -z "$UCORE_PATH" ]; then

    # replacing the value of devPath in the path, so avoiding to prepend it again
    if [[ $PATH == *"$UCORE_PATH"* ]]; then
        addBasePath=false
        export PATH=`echo $PATH | sed "s#$UCORE_PATH#$newBasePath#"`
    fi
fi

# adding devPath to the PATH
if $addBasePath; then
    export PATH=$newBasePath$PATH
fi

export UCORE_PATH=$newBasePath

# executing user overrides
if ! [ -z "$UCORE_LOCAL" ]; then
    if [ -f "$UCORE_LOCAL/env/expandedVars" ]; then
        source "$UCORE_LOCAL/env/expandedVars"
    fi
fi
