#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
wrappersDir="$( dirname $dir )"

# checking if dev root is set
if [ -z "$UCORE_ROOT" ]; then
    echo "UCORE_ROOT IS NOT SET" >&2
    return
fi

# adding bin to the path
ucoreBinPath=""
if ! [ -z "$UCORE_LOCAL" ]; then
    if [ -d "$UCORE_LOCAL/bin" ]; then
        ucoreBinPath+="$UCORE_LOCAL/bin:"
    fi
fi

# avoiding to prepended to the system path for every single bash session by making
# sure bin is not included to the path yet.
ucoreBinPath+="$wrappersDir/bin"
if ! [ "$UCORE_BIN_PATH" == "$ucoreBinPath" ]; then
    export UCORE_BIN_PATH=$ucoreBinPath
    export PATH="$UCORE_BIN_PATH:$PATH"
fi

# executing user overrides
if ! [ -z "$UCORE_LOCAL" ]; then
    if [ -f "$UCORE_LOCAL/env/expandedVars" ]; then
        source "$UCORE_LOCAL/env/expandedVars"
    fi
fi
