#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
rootDir="$(dirname $dir)"

# updating umedia deamon (auto-start script for kde/gnome):
if ! [ -d "$HOME/.config/autostart" ]; then
  mkdir -p ~/.config/autostart
fi

cp $rootDir/settings/defaultUserConfigs/autostart/*.desktop ~/.config/autostart/
