#!/bin/bash

# This file contains only enviroment variables that don't contain unresolved values,
# it is mainly used to set variables that contain versions which later on are used
# by the script "expandedVars" to resolve paths.
#
# Base vars can be overridden by user enviroment. Also, it can be overridden in the bash
# session by simply overriding the value of the variable then calling the alias "ucoreExpandVars"
# to resolve the variables that include ucore environment variables in their value.

# checking if dev root is set
if [ -z "$UCORE_ROOT" ]; then
    echo "UCORE_ROOT IS NOT SET" >&2
    return
fi

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# executing local overrides
if ! [ -z "$UCORE_LOCAL" ]; then
    if [ -f "$UCORE_LOCAL/env/ucoreVars" ]; then
        source "$UCORE_LOCAL/env/ucoreVars"
    fi
fi

# rez support
rez="$UAPPS_ROOT/rez/$UVER_REZ_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION"
if [ -d "$rez" ]; then
  # adding it to the path
  export PATH="$rez/bin/rez:$PATH"

  # sourcing auto-completion
  source "$rez/completion/complete.sh"
else
  # should throw an error message in case it was not found
  echo "Error: Could not find rez version $UVER_REZ_VERSION for the current platform/os ($UCORE_OS/$UCORE_OS_VERSION)!" >&2
fi

# calling expanded vars
source $dir/expandedVars

# calling custom envs
source $dir/extend
