#!/bin/bash

# This file contains only enviroment variables that don't contain unresolved values,
# it is mainly used to set variables that contain versions which later on are used
# by the script "expandedVars" to resolve paths.
#
# Base vars can be overridden by user enviroment. Also, it can be overridden in the bash
# session by simply overriding the value of the variable then calling the alias "ucoreExpandVars"
# to resolve the variables that include ucore environment variables in their value.

# checking if dev root is set
if [ -z "$UCORE_ROOT" ]; then
    echo "UCORE_ROOT IS NOT SET" >&2
    return
fi

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# executing local overrides
if ! [ -z "$UCORE_LOCAL" ]; then
    if [ -f "$UCORE_LOCAL/env/ucoreVars" ]; then
        source "$UCORE_LOCAL/env/ucoreVars"
    fi
fi

# calling expanded vars
source $dir/expandedVars

# calling custom envs
source $dir/extend
