#!/usr/bin/python

import time
import os
import signal
from subprocess import call


class UMediaDeamon(object):
    """
    Triggers the execution of login and logout scripts
    """

    def __init__(self):
        """
        Creates a deamon
        """

        self.__eventsPath = os.path.dirname(os.path.realpath(__file__))
        self.__runDeamon = True

        # connecting the termination events
        signal.signal(signal.SIGINT, self.stop)
        signal.signal(signal.SIGTERM, self.stop)

    def run(self):
        """
        Starts the deamon by performing the login scripts
        """

        runLogin = os.path.join(self.__eventsPath, 'login', 'run')
        call([runLogin])

        while self.__runDeamon:
            time.sleep(1)

    def stop(self, *args, **kwargs):
        """
        Finishes the deamon by performing the logout scripts
        """

        self.__runDeamon = False

        runLogout = os.path.join(self.__eventsPath, 'logout', 'run')
        call([runLogout])

# starting deamon
if __name__ == "__main__":
    deamon = UMediaDeamon();
    deamon.run()
