#!/bin/bash

source $UCORE_ROOT/util/queryVersion

# executing nuke
unset QT_PLUGIN_PATH;

# querying nuke major version
nukeMajorVersion=`majorVersion $UCORE_NUKE_VERSION`

# nuke plugins path
nukePluginsPath=$UPLUGINS_ROOT/nuke/$nukeMajorVersion

# ofx plugin names (separated by space)
ofxPluginNames="neatVideo"

# adding automatically the list of the ofx plugin names to the OFX_PLUGIN_PATH
for ofxPluginName in $ofxPluginNames ; do
  ofxPluginVarName="UCORE_${ofxPluginName^^}_VERSION"
  ofxPluginVarValue="${!ofxPluginVarName}"
  ofxPluginPathResolved=$nukePluginsPath/$ofxPluginName/$ofxPluginVarValue/bin/$UCORE_OS/$UCORE_OS_VERSION

  export OFX_PLUGIN_PATH=$ofxPluginPathResolved:$OFX_PLUGIN_PATH
done

# launching nuke
cd "$UAPPS_ROOT/nuke/$UCORE_NUKE_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION"
exec "./nuke" "$@"
