#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# root directory
rootDir="$( dirname $dir )"

source $rootDir/util/queryVersion

# executing nuke
unset QT_PLUGIN_PATH;

# querying nuke major version
nukeMajorVersion=`majorVersion $UVER_NUKE_VERSION`

# nuke plugins path
nukePluginsPath=$UPLUGINS_ROOT/nuke/$nukeMajorVersion

# ofx plugin names (separated by space)
ofxPluginNames=""

# adding automatically the list of the ofx plugin names to the OFX_PLUGIN_PATH
for ofxPluginName in $ofxPluginNames ; do
  ofxPluginVarName="UVER_${ofxPluginName^^}_VERSION"
  ofxPluginVarValue="${!ofxPluginVarName}"
  ofxPluginPathResolved=$nukePluginsPath/$ofxPluginName/$ofxPluginVarValue/bin/$UCORE_OS/$UCORE_OS_VERSION

  export OFX_PLUGIN_PATH=$ofxPluginPathResolved:$OFX_PLUGIN_PATH
done

# launching nuke
exec $UAPPS_ROOT/nuke/$UVER_NUKE_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/Nuke* "$@"
