#!/bin/bash

pythonExecutable="$UAPPS_ROOT/python/$UVER_UPYTHON_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/bin/python"

# getting current python version
executableVersion=$(pythonversion $pythonExecutable)

# pylama root
pylamaRoot="$ULIBS_ROOT/pylama/$UVER_PYLAMA_VERSION"
pylamaLib="$pylamaRoot/lib/python$executableVersion/site-packages"

# adding libraries to the python path
export PYTHONPATH=$pylamaLib:$PYTHONPATH

# executing pylama
exec upython "$pylamaRoot/bin/pylama" "$@"
