#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# root directory
rootDir="$( dirname $dir )"

source $rootDir/util/queryVersion

pythonExecutable="$UAPPS_ROOT/python/$UVER_UPYTHON_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/bin/python"

# getting current python version
executableVersion=$(pythonVersion $pythonExecutable)

# pytest root
pytestRoot="$ULIBS_ROOT/pytest/$UVER_PYTEST_VERSION"
pytestLib="$pytestRoot/lib/python$executableVersion/site-packages"

# adding libraries to the python path
export PYTHONPATH=$pytestLib:$PYTHONPATH

# executing pytest
exec upython "$pytestRoot/bin/pytest" "$@"
