#!/bin/bash

pythonExecutable="$UAPPS_ROOT/python/$UVER_UPYTHON_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/bin/python"

# getting current python version
executableVersion=$(pythonversion $pythonExecutable)

# pytest root
pytestRoot="$ULIBS_ROOT/pytest/$UVER_PYTEST_VERSION"
pytestLib="$pytestRoot/lib/python$executableVersion/site-packages"

# adding libraries to the python path
export PYTHONPATH=$pytestLib:$PYTHONPATH

# executing pytest
exec upython "$pytestRoot/bin/pytest" "$@"
