#!/bin/bash

# executing rv
unset QT_PLUGIN_PATH;

# setting the default shotgun url and login
export RV_SHOTGUN_DEFAULT_SERVER_URL="umedia.shotgunstudio.com"
export RV_SHOTGUN_DEFAULT_LOGIN="$USERNAME"

exec "$UAPPS_ROOT/rv/$UCORE_RV_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/bin/rv" "$@"
