#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# root directory
rootDir="$( dirname $dir )"

source $rootDir/util/queryVersion

pythonExecutable="$UAPPS_ROOT/python/$UVER_UPYTHON_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/bin/python"

# getting current python version
executableVersion=$(pythonVersion $pythonExecutable)

# tank library
tankLibrary="$ULIBS_ROOT/tank/$UVER_TANK_VERSION/lib/python$executableVersion"

# setuptools library
setuptoolsLib="$ULIBS_ROOT/setuptools/$UVER_SETUPTOOLS_VERSION/lib/python$executableVersion/site-packages"

# adding libraries to the python path
export PYTHONPATH=$tankLibrary:$setuptoolsLib:$PYTHONPATH

# executing upython
exec $pythonExecutable "$@"
