#!/bin/bash

#                    n,
#                  _/ | _
#                 /'  `'/
#               <~    .'
#               .'    |
#             _/      |
#           _/      `.`.
#      ____/ '   \__ | |______
#   __/___/      /__\ \ \     \___
#  /  (___.'\_______)\_|_|        \
# |\________                       ~~~~~\
# ||       |\___________________________/|
#
# ucore is responsable for initialization of the infrastructure used
# by apps that run on top upipe

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# detecting the current os
if [ "$(uname)" == "Darwin" ]; then
    export UCORE_OS="osx"

    # in osx ignoring the last part of product version (xx.xx.XX) is about the system update version,
    # since apps should be completly compatible accross them there is no need to include it as part of
    # the os version
    export UCORE_OS_VERSION=`sw_vers -productVersion | grep -oE '[0-9]*.[0-9]*' | head -n 1`

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    export UCORE_OS="linux"

    # figuring out the linux version (centos or ubuntu)
    {
      # centos
      osName=$(cat /etc/*elease | grep ID= | grep -oE '[a-z]*' | head -n 1)
      osVersion=$(cat /etc/*elease | grep VERSION_ID= | grep -oE '[0-9]*' | head -n 1)
    } || {
      # ubuntu
      osName=$(cat /etc/lsb-release | grep -Po '(?<=DISTRIB_ID=).*')
      osVersion=$(cat /etc/lsb-release | grep -Po '(?<=DISTRIB_RELEASE=).*')
    }

    export UCORE_OS_VERSION=$osName$osVersion

elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    export UCORE_OS="windows"
fi

# initializing
if [ -z "$UCORE_OS_VERSION" ]; then
    echo "COULD NOT RESOLVE UCORE_OS_VERSION!" >&2

else
    source $dir/env
fi

# executing the input command (if applicable)
if ! [ -z "$1" ] ; then
    eval "$1"
fi
