#!/bin/bash

#                    n,
#                  _/ | _
#                 /'  `'/
#               <~    .'
#               .'    |
#             _/      |
#           _/      `.`.
#      ____/ '   \__ | |______
#   __/___/      /__\ \ \     \___
#  /  (___.'\_______)\_|_|        \
# |\________                       ~~~~~\
# ||       |\___________________________/|
#
# usys is used to provide system information

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# detecting the current os
if [ "$(uname)" == "Darwin" ]; then
    export USYS_OS="osx"

    # in osx ignoring the last part of product version (xx.xx.XX) is about the system update version,
    # since apps should be completly compatible accross them there is no need to include it as part of
    # the os version
    export USYS_OS_VERSION=`sw_vers -productVersion | grep -oE '[0-9]*.[0-9]*' | head -n 1`

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    export USYS_OS="linux"

    # figuring out the linux version (centos or ubuntu)
    {
      # centos
      osName=$(cat /etc/*elease | grep ID= | grep -oE '[a-z]*' | head -n 1)
      osVersion=$(cat /etc/*elease | grep VERSION_ID= | grep -oE '[0-9]*' | head -n 1)
    } || {
      # ubuntu
      osName=$(cat /etc/lsb-release | grep -Po '(?<=DISTRIB_ID=).*')
      osVersion=$(cat /etc/lsb-release | grep -Po '(?<=DISTRIB_RELEASE=).*')
    }

    export USYS_OS_VERSION=$osName$osVersion

elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    export USYS_OS="windows"
fi

# initializing
if [ -z "$USYS_OS_VERSION" ]; then
    echo "COULD NOT RESOLVE USYS_OS_VERSION!" >&2
fi

# tells what is the host type, for instance 'company-wk-0003' results 'wk'
# Note: this can be overridden through a "postInit" script inside of sys-config
export USYS_HOST_TYPE=`echo $HOSTNAME | grep -oE '[a-z]*' | head -n 2 | tail -n 1`

# used to write metadata information (keep in mind the data under this folder
# is volatile)
export USYS_LOCAL_DATA="$HOME/.local/share/upipe"
